# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db645ce0fc705162edafac42f26bd535bd913baf7b03799a1a62d6f53852b6645413271cd931dd085155c6b3af5d20802767d65cf22f0d397150dda11e37ca16

test:
  secret_key_base: 2d50ae617bdf50e26b8809ffeafb064b905839b6226fb0731758dfbab35698b1c3143418eae79a61d217fa3840e1d9cd1839a9c8d10d45e12a524e34cd0eb72c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
